model_name: CenterNet


data:
  train_annotation_path: /home/ubuntu/wangchao/dataset/coco/annotations/instances_train2017.json
  val_annotation_path: /home/ubuntu/wangchao/dataset/coco/annotations/instances_val2017.json
  train_img_root: /home/ubuntu/wangchao/dataset/coco/train2017
  val_img_root: /home/ubuntu/wangchao/dataset/coco/val2017
  img_size: 512
  use_crowd: False
  batch_size: 16
  num_workers: 4
  debug: False
  remove_blank: True



model:
  num_cls: 80
  PIXEL_MEAN: [0.485, 0.456, 0.406]
  PIXEL_STD: [0.229, 0.224, 0.225]
  backbone: resnet50
  DECONV_CHANNEL: [2048, 256, 128, 64]
  DECONV_KERNEL: [4, 4, 4]
  MODULATE_DEFORM: True
  BIAS_VALUE: -2.19
  DOWN_SCALE: 4
  MIN_OVERLAP: 0.7
  TENSOR_DIM: 128
  freeze_bn: False
  output_size: [128, 128]



hyper_params:
  cls_weight: 1
  wh_weight: 0.1
  reg_weight: 1
  multi_scale: [512]


optim:
  optimizer: Adam
  lr: 0.0001
  momentum: 0.9
  milestones: [87,117]
  cosine_weights: 1.0
  warm_up_epoch: 1.
  max_norm: 5
  weight_decay: 0.0001
  epochs: 140
  sync_bn: True


val:
  interval: 1
  weight_path: weights
  max_det: 300


gpus: 0,1,2,3,4,5,6,7